//! The Settings page's words, one file per key and every language in each file (docs/i18n.md). Written by
//! `atelier-translate --batch strings/manifest.tsv`; add a key to the manifest, not by hand.
mod settings;
mod section_appearance;
mod section_sidebar;
mod section_agents;
mod section_dictation;
mod section_tasks;
mod section_keys;
mod gist_appearance;
mod gist_sidebar;
mod gist_agents;
mod gist_dictation;
mod gist_tasks;
mod gist_keys;
mod mode_light;
mod mode_dark;
mod mode_system;
mod theme;
mod mode;
mod interface_font_size;
mod primary_colour;
mod primary_colour_gist;
mod default_colour;
mod colour_blue;
mod colour_purple;
mod colour_pink;
mod colour_red;
mod colour_orange;
mod colour_amber;
mod colour_green;
mod colour_teal;
mod language;
mod language_system;
mod language_gist;
mod project_badge_on_rows;
mod time_on_rows;
mod agent_icon_on_rows;
mod sessions_shown_for_each_project;
mod earlier_sessions_shown_in_priority;
mod tool_calls;
mod tool_density_grouped;
mod tool_density_lines;
mod tool_density_detailed;
mod run_a_skill_when_you_pick_it;
mod no_model_to_pick;
mod no_agent_is_available;
mod dictation_key;
mod dictation_key_off;
mod microphone;
mod hold_the_microphone_button_to_record;
mod dictation_gist_fn_mac;
mod dictation_gist_shortcut_mac;
mod dictation_gist_none;

pub use settings::SETTINGS;
pub use section_appearance::SECTION_APPEARANCE;
pub use section_sidebar::SECTION_SIDEBAR;
pub use section_agents::SECTION_AGENTS;
pub use section_dictation::SECTION_DICTATION;
pub use section_tasks::SECTION_TASKS;
pub use section_keys::SECTION_KEYS;
pub use gist_appearance::GIST_APPEARANCE;
pub use gist_sidebar::GIST_SIDEBAR;
pub use gist_agents::GIST_AGENTS;
pub use gist_dictation::GIST_DICTATION;
pub use gist_tasks::GIST_TASKS;
pub use gist_keys::GIST_KEYS;
pub use mode_light::MODE_LIGHT;
pub use mode_dark::MODE_DARK;
pub use mode_system::MODE_SYSTEM;
pub use theme::THEME;
pub use mode::MODE;
pub use interface_font_size::INTERFACE_FONT_SIZE;
pub use primary_colour::PRIMARY_COLOUR;
pub use primary_colour_gist::PRIMARY_COLOUR_GIST;
pub use default_colour::DEFAULT_COLOUR;
pub use colour_blue::COLOUR_BLUE;
pub use colour_purple::COLOUR_PURPLE;
pub use colour_pink::COLOUR_PINK;
pub use colour_red::COLOUR_RED;
pub use colour_orange::COLOUR_ORANGE;
pub use colour_amber::COLOUR_AMBER;
pub use colour_green::COLOUR_GREEN;
pub use colour_teal::COLOUR_TEAL;
pub use language::LANGUAGE;
pub use language_system::LANGUAGE_SYSTEM;
pub use language_gist::LANGUAGE_GIST;
pub use project_badge_on_rows::PROJECT_BADGE_ON_ROWS;
pub use time_on_rows::TIME_ON_ROWS;
pub use agent_icon_on_rows::AGENT_ICON_ON_ROWS;
pub use sessions_shown_for_each_project::SESSIONS_SHOWN_FOR_EACH_PROJECT;
pub use earlier_sessions_shown_in_priority::EARLIER_SESSIONS_SHOWN_IN_PRIORITY;
pub use tool_calls::TOOL_CALLS;
pub use tool_density_grouped::TOOL_DENSITY_GROUPED;
pub use tool_density_lines::TOOL_DENSITY_LINES;
pub use tool_density_detailed::TOOL_DENSITY_DETAILED;
pub use run_a_skill_when_you_pick_it::RUN_A_SKILL_WHEN_YOU_PICK_IT;
pub use no_model_to_pick::NO_MODEL_TO_PICK;
pub use no_agent_is_available::NO_AGENT_IS_AVAILABLE;
pub use dictation_key::DICTATION_KEY;
pub use dictation_key_off::DICTATION_KEY_OFF;
pub use microphone::MICROPHONE;
pub use hold_the_microphone_button_to_record::HOLD_THE_MICROPHONE_BUTTON_TO_RECORD;
pub use dictation_gist_fn_mac::DICTATION_GIST_FN_MAC;
pub use dictation_gist_shortcut_mac::DICTATION_GIST_SHORTCUT_MAC;
pub use dictation_gist_none::DICTATION_GIST_NONE;
